API/Controllers/AddressController.cs
using Infrastructure.Entities;
using Infrastructure.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    public class AddressController : Controller
    {
        private readonly IGenericRepository<Address> _genericRepository;
        public readonly ICustomerRepository _customerRepository;

        public AddressController(IGenericRepository<Address> genericRepository,ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
            _genericRepository = genericRepository;
        }

        public IActionResult ListAddress(int id)
        {
            Customer customer = _customerRepository.GetById(id);

            return View(customer);
        }

        [HttpGet]
        public IActionResult CreateAddress(int id)
        {
            Address address = new Address { CustomerId = id };
            return View(address);
        }

        [HttpPost]
        public IActionResult CreateAddress(Address address)
        {
            address.Id = 0;
            _genericRepository.Add(address);
            return RedirectToAction("ListAddress", new { Id = address.CustomerId });
        }

        [HttpGet]
        public IActionResult UpdateAddress(int id)
        {
            Address address = _genericRepository.GetById(id);
            return View(address);
        }
        [HttpPost]
        public IActionResult UpdateAddress(Address address)
        {
            _genericRepository.Update(address);
            return RedirectToAction("ListAddress", new { Id = address.CustomerId });
        }
        public IActionResult DeleteAddress(int id, int customerId)
        {
            Address customerAddress = _genericRepository.GetById(id);
            _genericRepository.Delete(customerAddress);
            return RedirectToAction("ListAddress", new { Id = customerId });
        }
    }
}

API/Controllers/CustomerController.cs
using API.Dtos;
using API.Helper;
using Infrastructure.Entities;
using Infrastructure.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        private readonly ICustomerMapper _customerMapper;
        public CustomerController(ICustomerRepository customerRepository,ICustomerMapper customerMapper)
        {
            _customerRepository = customerRepository;
            _customerMapper = customerMapper;
        }

        public IActionResult Index()
        {
            return View();
        }       
        public IActionResult ListCustomer()
        {
            IReadOnlyList<Customer> customers = _customerRepository.ListAll();
            return View(customers);
        }
        [HttpGet]
        public IActionResult CreateCustomer()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult CreateCustomer(CustomerDto customerDto)
        {
            Customer customer = _customerMapper.CustomerDtoToCustomer(customerDto);

            _customerRepository.Add(customer);

            return RedirectToAction("ListCustomer");
        }
        [HttpGet]
        public IActionResult UpdateCustomer(int id)
        {
            Customer customer = _customerRepository.GetById(id);
            return Ok(customer);
        }
        [HttpPost]
        public IActionResult UpdateCustomer(Customer customer)
        {            
            _customerRepository.Update(customer);
            return RedirectToAction("ListCustomer");
        }
        public IActionResult DeleteCustomer(int id)
        {
            Customer customer = _customerRepository.GetById(id);
            _customerRepository.Delete(customer);

            return RedirectToAction("ListCustomer");
        }

    }
}

API/Controllers/MailController.cs
using Infrastructure.Entities;
using Infrastructure.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    public class MailController : Controller
    {
        private readonly IGenericRepository<CustomerMail> _genericRepository;
        public readonly ICustomerRepository _customerRepository;

        public MailController(IGenericRepository<CustomerMail> genericRepository, ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
            _genericRepository = genericRepository;
        }

        //Mail
        [HttpGet]
        public IActionResult ListMail(int id)
        {
            Customer customer = _customerRepository.GetById(id);

            return View(customer);
        }
        [HttpGet]
        public IActionResult CreateMail(int id)
        {
            CustomerMail mail = new CustomerMail { CustomerId = id };
            return View(mail);
        }
        [HttpPost]
        public IActionResult CreateMail(CustomerMail customerMail)
        {
            customerMail.Id = 0;
            _genericRepository.Add(customerMail);
            return RedirectToAction("ListMail", new { Id = customerMail.CustomerId });
        }
        [HttpGet]
        public IActionResult UpdateMail(int id)
        {
            CustomerMail customerMail = _genericRepository.GetById(id);
            return View(customerMail);
        }
        [HttpPost]
        public IActionResult UpdateMail(CustomerMail customerMail)
        {
            _genericRepository.Update(customerMail);
            return RedirectToAction("ListMail", new { Id = customerMail.CustomerId });
        }
        public IActionResult DeleteMail(int id,int customerId)
        {
            CustomerMail customerMail = _genericRepository.GetById(id);
            _genericRepository.Delete(customerMail);
            return RedirectToAction("ListMail", new { Id = customerId });
        }
    }
}

API/Controllers/PhoneController.cs
using Infrastructure.Entities;
using Infrastructure.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    public class PhoneController : Controller
    {
        private readonly IGenericRepository<CustomerPhone> _genericRepository;
        public readonly ICustomerRepository _customerRepository;

        public PhoneController(IGenericRepository<CustomerPhone> genericRepository, ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
            _genericRepository = genericRepository;
        }

        //Mail
        [HttpGet]
        public IActionResult ListPhone(int id)
        {
            Customer customer = _customerRepository.GetById(id);

            return View(customer);
        }

        [HttpGet]
        public IActionResult CreatePhone(int id)
        {
            CustomerPhone customerPhone = new CustomerPhone { CustomerId = id };
            return View(customerPhone);
        }

        [HttpPost]
        public IActionResult CreatePhone(CustomerPhone customerPhone)
        {
            customerPhone.Id = 0;
            _genericRepository.Add(customerPhone);
            return RedirectToAction("ListPhone", new { Id = customerPhone.CustomerId });
        }

        [HttpGet]
        public IActionResult UpdatePhone(int id)
        {
            CustomerPhone customerPhone = _genericRepository.GetById(id);
            return View(customerPhone);
        }

        [HttpPost]
        public IActionResult UpdatePhone(CustomerPhone phone)
        {
            _genericRepository.Update(phone);
            return RedirectToAction("ListPhone", new { Id = phone.CustomerId });
        }
        public IActionResult DeletePhone(int id, int customerId)
        {
            CustomerPhone customerPhone = _genericRepository.GetById(id);
            _genericRepository.Delete(customerPhone);
            return RedirectToAction("ListPhone", new { Id = customerId });
        }
    }
}

API/Views/Customer/CreateCustomer.cshtml
@model API.Dtos.CustomerDto

@{
    ViewData["Title"] = "View";
}

<h1>Create Customer</h1>

<hr />
<form asp-action="CreateCustomer">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="TcKimlik" class="control-label"></label>
                <input asp-for="TcKimlik" class="form-control" />
                <span asp-validation-for="TcKimlik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.State" class="control-label"></label>
                <input asp-for="Address.State" class="form-control" />
                <span asp-validation-for="Address.State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.ZipCode" class="control-label"></label>
                <input asp-for="Address.ZipCode" class="form-control" />
                <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="CustomerMail.Mail" class="control-label"></label>
                <input asp-for="CustomerMail.Mail" class="form-control" />
                <span asp-validation-for="CustomerMail.Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber.PhoneNumber" class="control-label"></label>
                <input asp-for="CustomerPhoneNumber.PhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber.PhoneNumber" class="text-danger"></span>
            </div>

        </div>




        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

API/Views/Customer/ListCustomer.cshtml
@model IEnumerable<Infrastructure.Entities.Customer>

@{
    ViewData["Title"] = "ListCustomer";
}

<h1>Customers</h1>

<p>
    <a asp-action="CreateCustomer">Create New Customer</a>
</p>
<script type="text/javascript" charset="utf8">
    $(document).ready(function () {
        $('#tbl1').DataTable();
    });
</script>
<table id="tbl1" class="table">
    <thead>
        <tr>
            <th>
                Tc Kimlik
            </th>
            <th>
               Name
            </th>
            <th>
                Lastname
            </th>
            <th>
                Email
            </th>
            <th>
                Phone
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TcKimlik)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mails[0].Mail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumbers[0].PhoneNumber)
                </td>
                <td>
                    @Html.ActionLink("Adresses", "ListAddress", "Address", new { id = item.Id }) |
                    @Html.ActionLink("Mails", "ListMail", "Mail", new { id = item.Id }) |
                    @Html.ActionLink("Phones", "ListPhone", "Phone", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "DeleteCustomer", "Customer", new { id = item.Id }) |
                    @Html.ActionLink("Update", "UpdateCustomer", "Customer", new { id = item.Id }) |
                </td>
            </tr>
        }
    </tbody>
</table>

API/Views/Customer/UpdateAddress.cshtml
@model Infrastructure.Entities.Customer

@{
    ViewData["Title"] = "UpdateAddress";
}

<h1>UpdateAddress</h1>

<p>
    <a asp-action="CreateAddress" asp-route-id="@Model.Id">Create New</a>
</p>
<table class="table">
    <h1>@Html.DisplayFor(model => model.Name)</h1>
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                City
            </th>
            <th>
                Street
            </th>
            <th>
                State
            </th>
            <th>
                Zipcode
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Addresses) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Street)                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

API/Views/Customer/UpdateCustomer.cshtml
@model Infrastructure.Entities.Customer

@{
    ViewData["Title"] = "UpdateCustomer";
}

<h1>Update Customer</h1>

<hr />

<form asp-action="UpdateCustomer">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" class="form-control" type="hidden" />

            <div class="form-group">
                <label asp-for="TcKimlik" class="control-label"></label>
                <input asp-for="TcKimlik" class="form-control" />
                <span asp-validation-for="TcKimlik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}